server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:h2:mem:notificationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: personel.notifications@gmail.com
    password: qejcxrzrphloefbj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

personnel-service:
  url: http://localhost:8081

auth-service:
  url: http://localhost:8082

logging:
  level:
    root: INFO
    com.example.notificationservice: INFO
    org.springframework.amqp: WARN
    org.springframework.amqp.rabbit: WARN
    org.springframework.amqp.rabbit.listener: WARN
    org.springdoc: WARN
    org.springframework.cloud.netflix.eureka: WARN
    com.netflix.discovery: WARN
